# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soft/perf_func/obj/allbench/axi_ram.coe
read_verilog {
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/defines.vh
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/defines2.vh
}
read_verilog -library xil_defaultlib {
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/ReadData_handle.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/WriteData_handle.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/adder.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/alu.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/alu_dec.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/axi_wrap/axi_wrap.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/ram_wrap/axi_wrap_ram.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/branch_predict_global.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/branch_predict_local.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/bridge_1x2.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/bridge_2x1.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/cache.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/compete_predict.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/CONFREG/confreg.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/controller.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/cp0_reg.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/cpu_axi_interface.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/d_cache.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/d_sram2sraml.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/div_radix2.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/exceptiondec.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/flopenrc.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/flowmips.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/hazard.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/i_cache.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/i_sram2sraml.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/instdec.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/main_dec.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/mmu.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/mux2.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/mux3.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/my_mul.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/mycpu.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/mycpu_top.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/pc.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/regfile.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/signext.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/myCPU/sl2.v
  C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/soc_axi_lite_top.v
}
read_ip -quiet C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_ram/axi_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_ram/axi_ram_ooc.xdc]

read_ip -quiet C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
set_property used_in_synthesis false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc]

read_ip -quiet C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
set_property used_in_implementation false [get_files -all c:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files C:/Users/49393/Desktop/perf_test_v0.03/perf_test_v0.01/soc_axi_perf/run_vivado/soc_lite.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_axi_lite_top -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_axi_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_axi_lite_top_utilization_synth.rpt -pb soc_axi_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
